<?php

declare(strict_types=1);

/*
 * FrankenPHP Worker Mode Entry Point for TYPO3
 *
 * This file is the entry point for FrankenPHP worker mode.
 * It is auto-generated by the ochorocho/frankenphp Composer installer.
 * DO NOT EDIT THIS FILE.
 */

use Ochorocho\FrankenPhp\Worker\WorkerStateResetter;
use TYPO3\CMS\Core\Core\Bootstrap;
use TYPO3\CMS\Core\Core\SystemEnvironmentBuilder;
use TYPO3\CMS\Core\Http\Application as HttpApplication;
use TYPO3\CMS\Install\Http\Application as InstallApplication;

ignore_user_abort(true);

// Marker used by Ochorocho\FrankenPhp\EventListener\AddFrankenPhpModeToSystemInformation
// to distinguish worker-mode requests (this file) from per-request /index.php
// execution (the install-tool recovery path). Set once per worker process and
// remains true for every request the worker handles; not visible to /index.php
// since that runs in a fresh PHP interpreter.
const TYPO3_FRANKENPHP_WORKER_MODE = true;

// BOOT PHASE — runs once per worker process.
$classLoader = require __DIR__ . '/../../../../../../vendor/autoload.php';
SystemEnvironmentBuilder::run();

// Mirror public/index.php — Bootstrap needs to know whether to bring up the
// install tool. In worker mode the actual request URLs aren't known yet, so
// we pass false here and rely on the container probing below to fall back to
// InstallApplication when HttpApplication isn't available (e.g. settings.php
// missing → FailsafeContainer).
$container = Bootstrap::init($classLoader, false);

// FailsafeContainer (install-tool / no settings.php) doesn't load extension
// Services.yaml, so WorkerStateResetter is absent. Degrade gracefully —
// the install tool has no long-lived singleton state that matters.
$resetter = $container->has(WorkerStateResetter::class)
    ? $container->get(WorkerStateResetter::class)
    : null;
$snapshot = $resetter?->capture($container);

// Pick the application. In a fully-installed system HttpApplication is
// available. If only the install tool is available (settings.php missing),
// fall back to that. If neither is available the worker still has to keep
// running so FrankenPHP doesn't trip max_consecutive_failures — emit 500s
// from the request loop instead of fataling here.
//
// Only the class is decided here. The instance is fetched per request:
// the Application holds the RequestHandler / middleware chain by reference,
// and those are discarded by the resetter, so a boot-time instance would
// keep stale references.
$applicationClass = null;
if ($container->has(HttpApplication::class)) {
    $applicationClass = HttpApplication::class;
} elseif ($container->has(InstallApplication::class)) {
    $applicationClass = InstallApplication::class;
}

$workerLogFile = \TYPO3\CMS\Core\Core\Environment::getVarPath() . '/log/frankenphp-worker.log';
@mkdir(dirname($workerLogFile), 0775, true);
$isDevelopment = \TYPO3\CMS\Core\Core\Environment::getContext()->isDevelopment();

// REQUEST HANDLER — runs per incoming request.
$handler = static function () use ($container, $resetter, $snapshot, $applicationClass, $workerLogFile, $isDevelopment): void {
    // AbstractApplication::sendResponse() may clear all output buffers when
    // emitting SelfEmittableStreamInterface (file downloads). Without a fresh
    // ob_start, subsequent requests would have no output buffering.
    ob_start();

    try {
        if ($applicationClass === null) {
            throw new \RuntimeException(
                'TYPO3 worker boot incomplete: neither HttpApplication nor InstallApplication is '
                . 'available in the container. Check config/system/settings.php and var/cache/.'
            );
        }
        $resetStart = hrtime(true);
        $discarded = $resetter?->reset($snapshot, $container) ?? 0;
        if ($isDevelopment) {
            // Tuning aids: how many service instances the previous request left
            // behind (should stabilise after warm-up; growth means a leak) and
            // how long the reset itself took, in microseconds.
            header('X-FrankenPHP-Discarded: ' . $discarded);
            header('X-FrankenPHP-Reset-Us: ' . intdiv(hrtime(true) - $resetStart, 1000));
        }
        $container->get($applicationClass)->run();
    } catch (\Throwable $e) {
        // One-line summary always goes through PHP's normal log channel —
        // syslog / stderr / wherever error_log is configured to land.
        $requestLine = sprintf('%s %s', $_SERVER['REQUEST_METHOD'] ?? '?', $_SERVER['REQUEST_URI'] ?? '?');
        $traceText = sprintf(
            "[%s] %s\n  %s: %s\n  at %s:%d\n%s\n\n",
            date('c'),
            $requestLine,
            $e::class,
            $e->getMessage(),
            $e->getFile(),
            $e->getLine(),
            $e->getTraceAsString()
        );
        error_log('TYPO3 Worker Error: ' . $e->getMessage() . ' in ' . $e->getFile() . ':' . $e->getLine());
        // Full stack trace dumped to var/log/frankenphp-worker.log only in
        // development. In production this file would grow unbounded under
        // any sustained burst of exceptions; one-line error_log() above is
        // enough to flag the incident, and the developer can re-enable this
        // for ad-hoc debugging by editing TYPO3_CONTEXT in .env.
        if ($isDevelopment) {
            @file_put_contents($workerLogFile, $traceText, FILE_APPEND | LOCK_EX);
        }

        // Delegate to TYPO3's registered exception handler so client errors
        // (AbstractClientErrorException — rate limit, forbidden, not found)
        // render their intended 4xx page instead of a flat 500. Bootstrap
        // registers the handler via set_exception_handler() so we discover
        // it through the null-set round-trip.
        $registeredHandler = set_exception_handler(null);
        if ($registeredHandler !== null) {
            set_exception_handler($registeredHandler);
            try {
                $registeredHandler($e);
            } catch (\Throwable $nested) {
                @file_put_contents(
                    $workerLogFile,
                    "    registered exception handler also threw: " . $nested->getMessage() . "\n\n",
                    FILE_APPEND | LOCK_EX
                );
                if (!headers_sent()) {
                    header('HTTP/1.1 500 Internal Server Error');
                    header('Content-Type: text/plain');
                }
                echo $isDevelopment ? $traceText : 'Internal Server Error';
            }
        } else {
            // No TYPO3 handler available — our own last-resort response.
            if (!headers_sent()) {
                header('HTTP/1.1 500 Internal Server Error');
                header('Content-Type: text/plain');
            }
            echo $isDevelopment ? $traceText : 'Internal Server Error';
        }
    } finally {
        // PHP-FPM auto-commits sessions to disk at request shutdown;
        // FrankenPHP workers do not. Without this call, anything written to
        // $_SESSION during the request (e.g. the install tool's
        // BackendModuleController setting up the Typo3InstallTool session
        // before redirecting to its iframe AJAX endpoint) never lands on
        // disk before the browser's follow-up request reads it — surfacing
        // as "The Install Tool session expired" 403s across Maintenance /
        // Settings / Upgrade.
        if (session_status() === PHP_SESSION_ACTIVE) {
            session_write_close();
        }
        while (ob_get_level()) {
            ob_end_flush();
        }
    }
};

// WORKER LOOP — bounded by MAX_REQUESTS to mitigate memory leaks in third-party
// libraries that were never designed for long-running processes.
$maxRequests = (int)($_SERVER['MAX_REQUESTS'] ?? 0);
for ($nbRequests = 0; !$maxRequests || $nbRequests < $maxRequests; ++$nbRequests) {
    $keepRunning = \frankenphp_handle_request($handler);
    gc_collect_cycles();
    if (!$keepRunning) {
        break;
    }
}
